### ISSUE TITLE
Issues with Requirements Install

### ISSUE THREAD

**Issue by stark4n6** [seba7236/BrowserParser#2]
Getting this error when installing on Windows 11, Python v3.12.6

![image](https://github.com/user-attachments/assets/7b630e0d-b5aa-4a7a-8936-48b965aac332)

I installed the Microsoft C++ Build Tools too but maybe I missed something.

**Comment by seba7236** [comment]
Hi,

Unfortunately, Plyvel / LevelDB parsing is not currently supported on Windows, and it's unlikely to be supported anytime soon. However, you have a few options:

1. Use the compiled binary, which includes all functions except for push notification parsing.
2. Run the script using WSL (Windows Subsystem for Linux), which provides full functionality.
3. Comment out the following lines in every Python file within the lib/ directory, except for firefox.py, a_pb2.py, detectBrowser.py and output.py:
        * import plyvel
        * from lib.a_pb2 import NotificationDatabaseDataProto
        * parse_chromium_notifications(f"{directory}/Platform Notifications")

I would recommend option 2 if possible, as it provides full functionality.

I hope this explanation helps!

**Comment by stark4n6** [comment]
I'll see what I can get to work, excited to try this out.

I know CCL has some support for LevelDB that has worked on Windows before so maybe something to look at [https://github.com/cclgroupltd/ccl_chromium_reader/blob/master/tools_and_utilities/dump_leveldb.py](https://github.com/cclgroupltd/ccl_chromium_reader/blob/master/tools_and_utilities/dump_leveldb.py)
